version: 2

models:
  - name: orders
    description: "One record per order placed on the store"
    columns:
      - name: order_id
        description: The primary key of the model
        tests:
          - unique
          - not_null
